# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58b18b658c53be8f8d7672f50043c959ec7024e0483d84acb3e76f5082ea5f593e2b052b93bfe94a59162932645000abe39768406d8f1c737d497dd4a0567308

test:
  secret_key_base: 0d914f0aac761d9fe2302025839009416a776fa11681a87001db86c6788e01f824da886ce864a4e6cd3209b240301dcd8b650a30f635e138839365528e206859

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
